    const checklistDataTravel = [
       { "activity":"Travel", "Grouping": "Chargers+Electronics", "item": "Laptop + Charger + Headphone + Mouse" },
       { "activity":"Travel", "Grouping": "Chargers+Electronics", "item": "OnePlus Mobile + Charger + Headphone" },
       { "activity":"Travel", "Grouping": "Chargers+Electronics", "item": "Powerbank + Charger" },
       { "activity":"Travel", "Grouping": "Chargers+Electronics", "item": "Samsung Mobile + Charger" },
       { "activity":"Travel", "Grouping": "Chargers+Electronics", "item": "Samsung Watch + Charger" },
       { "activity":"Travel", "Grouping": "Chargers+Electronics", "item": "Tablet + Charger" },
       { "activity":"Travel", "Grouping": "Clothes - Formal", "item": "Jacket" },
       { "activity":"Travel", "Grouping": "Clothes - Formal", "item": "shirts" },
       { "activity":"Travel", "Grouping": "Clothes - Formal", "item": "shoe" },
       { "activity":"Travel", "Grouping": "Clothes - Formal", "item": "socks" },
       { "activity":"Travel", "Grouping": "Clothes - Formal", "item": "trousers" },
       { "activity":"Travel", "Grouping": "Clothes - Formal", "item": "tshirts - Polo" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "home bermuda : x4" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "homeshirts : x8" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "jeans" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "shoe" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "Slippers/Crocs" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "socks" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "tshirts : x7" },
       { "activity":"Travel", "Grouping": "Clothes - Informal", "item": "underwear : x9" },
       { "activity":"Travel", "Grouping": "Clothes - Rain", "item": "Mobile raincoat" },
       { "activity":"Travel", "Grouping": "Clothes - Rain", "item": "Umbrella/raincoat" },
       { "activity":"Travel", "Grouping": "Clothes - Winter", "item": "Home Cold Jacket" },
       { "activity":"Travel", "Grouping": "Clothes - Winter", "item": "Medium Cold Jacket" },
       { "activity":"Travel", "Grouping": "Clothes - Winter", "item": "VERY Cold Jacket" },
       { "activity":"Travel", "Grouping": "Clothes - Winter", "item": "Warm Socks" },
       { "activity":"Travel", "Grouping": "Documents", "item": "Aadhar or PAN Card" },
       { "activity":"Travel", "Grouping": "Documents", "item": "Driving License" },
       { "activity":"Travel", "Grouping": "Documents", "item": "Passport : x2" },
       { "activity":"Travel", "Grouping": "Documents", "item": "tickets" },
       { "activity":"Travel", "Grouping": "Extra", "item": "Local Currency" },
       { "activity":"Travel", "Grouping": "Extra", "item": "SIM" },
       { "activity":"Travel", "Grouping": "Extra", "item": "Travel Bag" },
       { "activity":"Travel", "Grouping": "Gym", "item": "Health Drink" },
       { "activity":"Travel", "Grouping": "Gym", "item": "Knee guard" },
       { "activity":"Travel", "Grouping": "Gym", "item": "Shaker" },
       { "activity":"Travel", "Grouping": "Gym", "item": "shoe" },
       { "activity":"Travel", "Grouping": "Gym", "item": "shorts" },
       { "activity":"Travel", "Grouping": "Gym", "item": "socks" },
       { "activity":"Travel", "Grouping": "Gym", "item": "Sports Bag" },
       { "activity":"Travel", "Grouping": "Gym", "item": "Swimming Trunk" },
       { "activity":"Travel", "Grouping": "Gym", "item": "towel" },
       { "activity":"Travel", "Grouping": "Gym", "item": "tshirts" },
       { "activity":"Travel", "Grouping": "Gym", "item": "Weighing Machine" },
       { "activity":"Travel", "Grouping": "Health", "item": "Masks" },
       { "activity":"Travel", "Grouping": "Health", "item": "Nose Spray" },
       { "activity":"Travel", "Grouping": "Leisure", "item": "Book" },
       { "activity":"Travel", "Grouping": "Leisure", "item": "harddisk" },
       { "activity":"Travel", "Grouping": "Leisure", "item": "Rubik" },
       { "activity":"Travel", "Grouping": "Leisure", "item": "Selfie Stick" },
       { "activity":"Travel", "Grouping": "Souvenir ", "item": "Souvenir" },
       { "activity":"Travel", "Grouping": "Toileteries", "item": "coconut oil" },
       { "activity":"Travel", "Grouping": "Toileteries", "item": "Comb" },
       { "activity":"Travel", "Grouping": "Toileteries", "item": "hair stuff" },
       { "activity":"Travel", "Grouping": "Toileteries", "item": "moov" },
       { "activity":"Travel", "Grouping": "Toileteries", "item": "perfume" },
       { "activity":"Travel", "Grouping": "Toileteries", "item": "Shaving" },
       { "activity":"Travel", "Grouping": "Toileteries", "item": "Toothbrush+ toothpaste" },
     ];
